apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ta2-train-
  annotations:
    email: 'jon.crall@kitware.com'
    purpose: |
      Check read access on DVC GitLab repo
    submitter: 'Jon Crall'
spec:
  entrypoint: ta2-train-init
  serviceAccountName: argo-runner
  imagePullSecrets:
    - name: crall-smartgitlab-secret
    #- name: gitlab-pull-secret
  nodeSelector:
    kitware.com/node-pool: gpu
    #kitware.com/node-pool: mixed
  volumes:
    - name: dvc-access-secret-volume
      secret:
        secretName: dvc-gitlab-access-token
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 8G
    - name: cachedir
      persistentVolumeClaim:
        claimName: ta2-data-volume
  templates:
  - name: ta2-train-init
    container:
      #image: gitlab.kitware.com:4567/smart/watch/training:{{inputs.parameters.container_tag}}
      #image: gitlab.kitware.com:4567/smart/watch/ta2_training_v2:{{inputs.parameters.container_tag}}
      #image: gitlab.kitware.com:4567/smart/watch/ta2_training_v2:981feb6592f2
      #image: gitlab.kitware.com:4567/smart/watch/ta2_training_v2
      image: registry.smartgitlab.com/kitware/watch/ta2_training_v2
      command: [bash]
      # The second arg is which branch should be used
      args: ["/root/code/watch/aws/train_remote_init.sh", "dev/flow49"]
      resources:
        #requests:
        #  memory: "32G"
        #  cpu: "15000m"
        #  #nvidia.com/gpu: 1
        #limits:
        #  memory: "64G"
        #  cpu: "15000m"
        #  #nvidia.com/gpu: 1
        #  #      resources:
        requests:
          memory: "28G"
          cpu: "3000m"
          nvidia.com/gpu: 1
        limits:
          memory: "30G"
          cpu: "3500m"
          nvidia.com/gpu: 1
      env:
        - name: DVC_GITLAB_USERNAME
          valueFrom:
            secretKeyRef:
              name: dvc-gitlab-access-token
              key: username
        - name: DVC_GITLAB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dvc-gitlab-access-token
              key: password
        - name: WATCH_REPO_GITLAB_RO_DEPLOY_USERNAME
          valueFrom:
            secretKeyRef:
              name: watch-repo-gitlab-ro-deploy-token
              key: username
        - name: WATCH_REPO_GITLAB_RO_DEPLOY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: watch-repo-gitlab-ro-deploy-token
              key: password
      volumeMounts:
        - name: dvc-access-secret-volume
          mountPath: "/secret/dvc-access-secret-mountpath"
        - name: dshm
          mountPath: /dev/shm
        - name: cachedir
          mountPath: /efsdata
