# Autogenerated via:
# python ~/code/watch/dev/maintain/mirror_package_geowatch.py
from watch.tasks.depth_pcd.filter_tracks import main


def __getattr__(key):
    import watch.tasks.depth_pcd.filter_tracks as mirror
    return getattr(mirror, key)


def __dir__():
    import watch.tasks.depth_pcd.filter_tracks as mirror
    return dir(mirror)


if __name__ == '__main__':
    main()
