# Ours
# location: server
location: local
data:
  type: semantic_seg
  name: iarpa
  image_size: 300x300
  num_classes: 5
  weights: []
  local:
    model_save_dir: /home/native/projects/data/smart_watch/models/
    train_dir: /media/native/data/data/smart_watch_dvc/drop0_aligned_msi/
    test_dir: /media/native/data/data/smart_watch_dvc/drop0_aligned_msi/
    coco_json: /media/native/data/data/smart_watch_dvc/drop0_aligned_msi/material_labels2.kwcoco.json
    val_dir:
  server:
    model_save_dir: /data4/peri/smart_watch/models/
    train_dir: /data4/peri/datasets/smart_watch/processed/drop0_aligned_v2.1/
    test_dir: /data4/peri/datasets/smart_watch/processed/drop0_aligned_v2.1/
    val_dir: /data4/peri/datasets/smart_watch/processed/drop0_aligned_v2.1/
    coco_json:  /data4/datasets/smart_watch/processed/drop0_aligned_v2.1/material_labels.kwcoco.json

training:
  backbone: 
  model_name: shallow_seg
  gn_n_groups: 32
  num_channels: 6
  weight_std: True
  beta: False
  pretrained: False
  distributed: False
  learning_rate: 0.0001 # best: 0.00007
  # resume: /home/native/projects/data/smart_watch/models/experiments_iarpa/tasks_experiments_2021-06-07-12:19/experiments_epoch_147_loss_3.3501133032334156_valmIoU_0.21981567095240662_time_2021-06-07-14:47:07.pth
  resume: False
  train_val_test_split: [0.95, 0.02, 0.03]
  epochs: 200
  start_epoch: 0
  batch_size: 2
  drop_last_batch: True
  momentum: 0.9
  weight_decay: 0.0001
  num_workers: 4
  test_with_full_supervision: 1

high_confidence_threshold:
  train_cutoff: 0.8
  val_cutoff: 0.8


evaluation:
  use_crf: False
  crf_t: 1
  crf_scale_factor: 1

procedures:
  train: True
  validate: True