# Ours
# location: server
location: local
data:
  type: semantic_seg
  name: iarpa
  num_classes: 40
  window_size: 7
  image_size: 128
  time_steps: 2
  weights: []
  channels: red|green|blue|nir|swir16|swir22
  local:
    model_save_dir: /home/native/projects/data/smart_watch/models/
    train_dir: /media/native/data/data/smart_watch_dvc/drop0_aligned_msi/
    test_dir: /media/native/data/data/smart_watch_dvc/drop0_aligned_msi/
    coco_json: /home/native/core534_data/datasets/smart_watch_dvc/drop0_aligned_msi_cf6/train.kwcoco.json
    val_dir:
  server:
    model_save_dir: /data4/peri/smart_watch/models/
    train_dir: /data4/peri/datasets/smart_watch/processed/drop0_aligned_v2.1/
    test_dir: /data4/peri/datasets/smart_watch/processed/drop0_aligned_v2.1/
    val_dir: /data4/peri/datasets/smart_watch/processed/drop0_aligned_v2.1/
    coco_json:  /data4/datasets/smart_watch/processed/drop0_aligned_v2.1/material_labels.kwcoco.json

training:
  backbone: #resnet18 #resnet101, resnet50
  model_name: shallow_seg #shallow_seg, deeplabWS
  model_feats_channels: [32, 32, 64, 64, 128] #[32, 32, 64, 64, 128], [64, 64, 128, 256, 512], [32, 32, 64, 128, 256] # this needs to match the correct number of layers in the model
  gn_n_groups: 32
  num_channels: 13
  out_features_dim: 10
  weight_std: True
  beta: False
  pretrained: False
  distributed: False
  learning_rate: 0.002 # best: 0.00007
  # resume: /home/native/projects/data/smart_watch/models/experiments_onera/tasks_experiments_onera_2021-08-06-22:35_baseline/experiments_epoch_49_loss_0.04315589724482366_valmIoU_0.5678595403613368_time_2021-08-07-15:25:56.pth
  resume: False
  train_val_test_split: [0.95, 0.02, 0.03]
  epochs: 200
  start_epoch: 0
  batch_size: 2
  drop_last_batch: True
  momentum: 0.9
  weight_decay: 0.0001
  num_workers: 4
  test_with_full_supervision: 1

high_confidence_threshold:
  train_cutoff: 0.4
  val_cutoff: 0.4
  train_low_cutoff: 0.0
  val_low_cutoff: 0.0

evaluation:
  use_crf: False
  crf_t: 1
  crf_scale_factor: 1
  inference_window: 7

procedures:
  train:  False
  validate: True