dataset: onera
use_cuda: True
seed: 11

visualization:
  batch_index_to_show: 0
  train_visualizer: True
  val_visualizer: True
  visualize_training_every: 2
  visualize_val_every: 4
  train_visualization_divisor: 221
  val_visualization_divisor: 114
  save_individual_plots: False
  save_individual_plots_train: False
  save_individual_plots_path: /home/native/projects/data/smart_watch/visualization/research_deep_dive_presentation_3/
  titles: True
  train_imshow: False
  val_imshow: False
  fg_alpha: 0.7
  bg_alpha: 0.8
  font_size: 8
  fig_size: 15

cometml:
  api_key: 9GTK1r9PK4NzMAoLsnC6XxI7p
  workspace: periakiva
