# Ours
# location: server
location: local
data:
  type: semantic_seg
  name: iarpa
  image_size: 128
  num_classes: 20
  window_size: 7
  time_steps: 2
  weights: []
  # channels: B02|B03|B04|B05|B06|B07|B08|B11|B12|B8A
  channels: B02|B03|B04|B05|B06|B07|B08|B11|B12
  local:
    model_save_dir: /home/native/projects/data/smart_watch/models/
    train_dir: /media/native/data/data/smart_watch_dvc/extern/onera_2018/
    test_dir: /media/native/data/data/smart_watch_dvc/extern/onera_2018/
    coco_json: /media/native/data/data/smart_watch_dvc/extern/onera_2018/onera_all.kwcoco.json
    val_dir:
  server:
    model_save_dir: /data4/peri/smart_watch/models/
    train_dir: /data4/datasets/smart_watch_dvc/extern/onera_2018/
    test_dir: /data4/datasets/smart_watch_dvc/extern/onera_2018/
    val_dir: /data4/datasets/smart_watch_dvc/extern/onera_2018/
    coco_json:  /data4/datasets/smart_watch_dvc/extern/onera_2018/onera_all.kwcoco.json

training:
  backbone: 
  model_name: shallow_seg
  gn_n_groups: 32
  num_channels: 13
  out_features_dim: 10
  weight_std: True
  beta: False
  pretrained: False
  distributed: False
  learning_rate: 0.002 # best: 0.00007
  # resume: /home/native/projects/data/smart_watch/models/experiments_onera/tasks_experiments_onera_2021-07-21-11:59/experiments_epoch_55_loss_0.9299376284428704_valmIoU_0_time_2021-07-21-13:32:06.pth
  resume: False
  train_val_test_split: [0.95, 0.02, 0.03]
  epochs: 200
  start_epoch: 0
  batch_size: 1
  drop_last_batch: True
  momentum: 0.9
  weight_decay: 0.0001
  num_workers: 4
  test_with_full_supervision: 1

high_confidence_threshold:
  train_cutoff: 0.3
  val_cutoff: 0.3

evaluation:
  use_crf: False
  crf_t: 1
  crf_scale_factor: 1

procedures:
  train:  True
  validate: True