# Autogenerated via:
# python ~/code/watch/dev/maintain/mirror_package_geowatch.py


def __getattr__(key):
    import geowatch.utils.lightning_ext._jsonargparse_ext_ge_4_21_and_lt_4_22 as mirror
    return getattr(mirror, key)


def __dir__():
    import geowatch.utils.lightning_ext._jsonargparse_ext_ge_4_21_and_lt_4_22 as mirror
    return dir(mirror)