# Autogenerated via:
# python ~/code/watch/dev/maintain/mirror_package_geowatch.py
from geowatch.tasks.rutgers_material_seg.scripts.filter_by_sensor import main


def __getattr__(key):
    import geowatch.tasks.rutgers_material_seg.scripts.filter_by_sensor as mirror
    return getattr(mirror, key)


def __dir__():
    import geowatch.tasks.rutgers_material_seg.scripts.filter_by_sensor as mirror
    return dir(mirror)


if __name__ == '__main__':
    main()
