# Autogenerated via:
# python ~/code/watch/dev/maintain/mirror_package_geowatch.py
from geowatch.tasks.rutgers_material_seg.scripts.labelbox2coco import from_json


def __getattr__(key):
    import geowatch.tasks.rutgers_material_seg.scripts.labelbox2coco as mirror
    return getattr(mirror, key)


def __dir__():
    import geowatch.tasks.rutgers_material_seg.scripts.labelbox2coco as mirror
    return dir(mirror)


if __name__ == '__main__':
    labeled_data = '/home/native/core534_data/datasets/smart_watch/processed/drop0_aligned_v2/labelbox_weak_labels.json'

    # set coco_output to the file name you want the COCO data to be written to
    coco_output = '/home/native/core534_data/datasets/smart_watch/processed/drop0_aligned_v2/fromlabelbox.kwcoco.json'

    # call the Labelbox to COCO conversion
    from_json(labeled_data=labeled_data, coco_output=coco_output)
