# Autogenerated via:
# python ~/code/watch/dev/maintain/mirror_package_geowatch.py
from watch.tasks.fusion.fit import main


def __getattr__(key):
    import watch.tasks.fusion.fit as mirror
    return getattr(mirror, key)


def __dir__():
    import watch.tasks.fusion.fit as mirror
    return dir(mirror)


if __name__ == '__main__':
    if ub.argflag('--warntb'):
        import xdev
        xdev.make_warnings_print_tracebacks()
    # from watch.tasks.fusion import fit as this_module
    # this_module.main()
    main()
