# Autogenerated via:
# python ~/code/watch/dev/maintain/mirror_package_geowatch.py
from watch.tasks.fusion.organize import fire


def __getattr__(key):
    import watch.tasks.fusion.organize as mirror
    return getattr(mirror, key)


def __dir__():
    import watch.tasks.fusion.organize as mirror
    return dir(mirror)


if __name__ == '__main__':
    import fire
    fire.Fire()
