# Autogenerated via:
# python ~/code/watch/dev/maintain/mirror_package_geowatch.py
def __getattr__(key):
    import watch.utils.lightning_ext._jsonargparse_ext_lt_4_21 as mirror
    return getattr(mirror, key)