---
name: watch
channels:
  - conda-forge
dependencies:
  - python=3.8
  - gdal
  - shapely=1.7.1
  - pip
  - pip:
    - algorithm_toolkit==0.2.0
    - numpy==1.19.5
    - Pillow==7.1.0
    - requests==2.20.0
    - pytest
    - xdoctest
    - pytest-cov
    - coverage
    - affine
    - utm
    - ubelt
    - pyproj >= 3.0.0.post1
    - rasterio >= 1.2.0
    # kitware tools
    - kwarray
    - kwimage
