---
name: watch
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python == 3.8
  - pip >= 21.0.1
  - pip:

    # Numeric
    - kwarray >= 0.5.19
    - numpy >= 1.20.0
    - scipy >= 1.6.3
    - shapely >= 1.7.1
    - pandas >= 1.2.4
    - xarray >= 0.17.0

    # Frameworks
    - algorithm_toolkit == 0.2.0

    # Testing
    - pytest >= 6.2.1
    - xdoctest >= 0.15.4 
    - pytest_cov >= 2.8.1
    - coverage >= 5.4

    # Utilities
    - psutil >= 5.8.0
    - xxhash >= 1.4.4
    - parse >= 1.14.0
    - affine >= 2.3.0
    - ubelt >= 0.9.5
    - xmltodict >= 0.12.0
    - pygments >= 2.6.1
    - requests >= 2.25.1
    - girder_client >= 3.1.0
    - lxml >= 4.6.3
    - tempenv >= 0.2.0
    - pystac_client >= 0.1.1
    - scriptconfig >= 0.5.8
    - pygtrie >= 2.3.3
    - protobuf >= 3.15.8
    - networkx >= 2.5.1
    - einops >= 0.3.0

    # Imaging
    - kwimage >= 0.7.8
    - kwcoco >= 0.2.5
    - Pillow >= 8.0.1
    - imgaug >= 0.4.0
    - albumentations >= 1.0.0
    - opencv_python_headless >= 4.5.2.52  # This can be a problem library
    - scikit_image >= 0.18.1
    - ndsampler >= 0.6.3
    - tifffile >= 2021.4.8

    # Plotting
    - matplotlib >= 3.4.1
    - kwplot >= 0.4.8
    - seaborn >= 0.11.1

    # GIS
    - geopandas >= 0.8.1
    - pyproj >= 3.0.0.post1
    - rasterio >= 1.2.0
    - rgdc >= 0.1.1
    - utm >= 0.7.0
    - fels >= 1.4.0

    # Machine learning
    - scikit_learn >= 0.24.2
    - torch >= 1.8.0
    - torch_liberator >= 0.1.0
    - torch_optimizer >= 0.1.0
    - pytorch_lightning >= 1.3.5
    - netharn >= 0.5.15
    
    - torchmetrics >= 0.3.2

    - tensorboard_logger >= 0.1.0 
    - tensorboard >= 2.4.1
      
    # find-links applies to everything after it, so make sure this is the last dep
    # References: https://stackoverflow.com/questions/60410173/find-links-conda-env
    - --find-links https://girder.github.io/large_image_wheels
    - GDAL >= 3.2.1


# Abuse conda environment spec and YAML notation to make a heredoc for notes
# and relevant commands
#variables:
.__doc__: &__doc__
  - |

      rm -rf ".cache/conda/envs/loose-watch-env"
      conda env create -f conda_env.yml --prefix ".cache/conda/envs/loose-watch-env" -v -v

      # List of other sub-deps not explicitly listed, but that will get
      # pulled down. Should these be added to the requirment spec
      Jinja2 >= 3.0.0
      MarkupSafe >= 2.0.0
      PyWavelets >= 1.1.1
      WTForms >= 2.3.3
      absl_py >= 0.12.0
      astunparse >= 1.6.3
      atomicwrites >= 1.4.0
      attrs >= 21.2.0
      bezier >= 2021.2.12
      cachetools >= 4.2.2
      chardet >= 4.0.0
      click >= 7.1.2
      click_plugins >= 1.1.1
      cligj >= 0.7.1
      configparser >= 5.0.2
      cycler >= 0.10.0
      decorator >= 4.4.2
      diskcache >= 5.2.1
      distro >= 1.5.0
      fasteners >= 0.16
      fiona >= 1.8.19
      flask >= 2.0.0
      flask_cors >= 3.0.10
      flask_wtf >= 0.14.3
      geomet >= 0.3.0
      girder_client >= 3.1.4
      google_auth >= 1.30.0
      google_auth_oauthlib >= 0.4.4
      grpcio >= 1.37.1
      idna >= 2.10
      imageio >= 2.9.0
      inflect >= 5.3.0
      iniconfig >= 1.1.1
      itsdangerous >= 2.0.0
      joblib >= 1.0.1
      jsonschema >= 3.2.0
      kiwisolver >= 1.3.1
      liberator >= 0.0.1
      markdown >= 3.3.4
      munch >= 2.5.0
      oauthlib >= 3.1.0
      ordered_set >= 4.0.2
      packaging >= 20.9
      pluggy >= 0.13.1
      py >= 1.10.0
      pyasn1 >= 0.4.8
      pyasn1_modules >= 0.2.8
      pyflakes >= 2.3.1
      pyparsing >= 2.4.7
      pyqtree >= 1.0.0
      pyrsistent >= 0.17.3
      pystac_client >= 0.1.1
      python_dateutil >= 2.8.1
      python_dotenv >= 0.17.1
      pytorch-ranger >= 0.1.1
      pytz >= 2021.1
      requests_oauthlib >= 1.3.0
      requests_toolbelt >= 0.9.1
      rsa >= 4.7.2
      six >= 1.16.0
      snuggs >= 1.4.7
      tabulate >= 0.8.9
      tensorboard_data_server >= 0.6.1
      tensorboard_plugin_wit >= 1.8.0
      threadpoolctl >= 2.1.0
      torchvision >= 0.9.1
      tqdm >= 4.60.0
      typing >= extensions >= 3.10.0.0
      uritools >= 3.0.2
      urllib3 >= 1.26.4
      werkzeug >= 2.0.0
      sortedcontainers >= 2.3.0
      toml >= 0.10.2
      pyyaml >= 5.4.1
