---
name: watch
channels:
  - conda-forge
dependencies:
  - python=3.8
  - gdal==3.0.2
  - shapely=1.7.1
  - pip
  - pip:
    - algorithm_toolkit==0.2.0
    - numpy==1.19.5
    - Pillow==7.1.0
    - requests==2.20.0
    - pytest
    - xdoctest
    - pytest-cov
    - coverage
    - parse >= 1.14.0
    - affine >= 2.3.0
    - utm >= 0.7.0
    - ubelt >= 0.9.5
    - pyproj >= 3.0.0.post1
    - rasterio >= 1.2.0
    - xmltodict >= 0.12.0
    - geopandas >= 0.8.1
    # kitware tools
    - kwarray
    - kwimage >= 0.7.0
    - kwcoco >= 0.1.12
    - girder_client >= 3.1.0
