---
name: watch
channels:
  - conda-forge
dependencies:
  - python == 3.8
  - pip >= 21.0.1
  - pip:
    # Core
    - numpy >= 1.20.0
    - shapely >= 1.7.1

    # Frameworks
    - algorithm_toolkit == 0.2.0

    # Testing
    - pytest >= 6.2.1
    - xdoctest >= 0.15.4 
    - pytest-cov >= 2.8.1
    - coverage >= 5.4

    # Utilities
    - xxhash >= 1.4.4
    - parse >= 1.14.0
    - affine >= 2.3.0
    - ubelt >= 0.9.5
    - xmltodict >= 0.12.0
    - pygments >= 2.6.1
    - requests >= 2.25.1
    - girder_client >= 3.1.0
    - lxml >= 4.6.3
    - tempenv >= 0.2.0
    - pystac-client >= 0.1.1

    # Image / numeric
    - kwarray >= 0.5.18
    - kwimage >= 0.7.3
    - kwcoco >= 0.2.2
    - Pillow >= 8.0.1
    - imgaug >= 0.4.0

    # GIS
    - utm >= 0.7.0
    - pyproj >= 3.0.0.post1
    - rasterio >= 1.2.0
    - geopandas >= 0.8.1
    - rgdc >= 0.1.1
    - git+https://git@github.com/matt-bernstein/fetchLandsatSentinelFromGoogleCloud.git

    # find-links applies to everything after it, so make sure this is the last dep
    # References: https://stackoverflow.com/questions/60410173/find-links-conda-env
    - --find-links https://girder.github.io/large_image_wheels
    - GDAL >= 3.2.1
