---
name: watch
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python == 3.8
  - pip >= 21.0.1
  - pip:
    - -r file:requirements/simple-deps.txt

    ## find-links applies to everything after it, so make sure this is the last dep
    ## References: https://stackoverflow.com/questions/60410173/find-links-conda-env
    #- --find-links https://girder.github.io/large_image_wheels
    #- GDAL >= 3.3.1


# Abuse conda environment spec and YAML notation to make a heredoc for notes
# and relevant commands
#variables:
.__doc__: &__doc__
  - |

      pip uninstall osgeo GDAL
      pip install GDAL==3.2.1 --find-links https://girder.github.io/large_image_wheels

      rm -rf ".cache/conda/envs/loose-watch-env"
      conda env create -f conda_env.yml --prefix ".cache/conda/envs/loose-watch-env" -v -v

      # Note: work in dev/make_reqs_from_conda.py has work on doing interesting
      # things with this file. 
