---
name: watch
channels:
  - conda-forge
dependencies:
  - python=3.8
  - gdal
  - pip
  - pip:
    - pytest
    - xdoctest
    - pytest-cov
    - coverage
    - affine
    - utm
    - ubelt
    - pyproj >= 3.0.0.post1
    - rasterio >= 1.2.0
    # kitware tools
    - kwarray
    - kwimage
