# Autogenerated via:
# python ~/code/watch/dev/maintain/mirror_package_geowatch.py
from watch.mlops.aggregate import main


def __getattr__(key):
    import watch.mlops.aggregate as mirror
    return getattr(mirror, key)


def __dir__():
    import watch.mlops.aggregate as mirror
    return dir(mirror)


if __name__ == '__main__':
    main()
