# Autogenerated via:
# python ~/code/watch/dev/maintain/mirror_package_geowatch.py
from watch.cli.stac_to_kwcoco import sys


def __getattr__(key):
    import watch.cli.stac_to_kwcoco as mirror
    return getattr(mirror, key)


def __dir__():
    import watch.cli.stac_to_kwcoco as mirror
    return dir(mirror)


if __name__ == '__main__':
    sys.exit(main())
