# Autogenerated via:
# python ~/code/watch/dev/maintain/mirror_package_geowatch.py
from watch.mlops.old.expt_manager import main


def __getattr__(key):
    import watch.mlops.old.expt_manager as mirror
    return getattr(mirror, key)


def __dir__():
    import watch.mlops.old.expt_manager as mirror
    return dir(mirror)


if __name__ == '__main__':
    main(cmdline=True)
