# Autogenerated via:
# python ~/code/watch/dev/maintain/mirror_package_geowatch.py
from watch.tasks.depth.predict import setup_logging, torch, predict


def __getattr__(key):
    import watch.tasks.depth.predict as mirror
    return getattr(mirror, key)


def __dir__():
    import watch.tasks.depth.predict as mirror
    return dir(mirror)


if __name__ == '__main__':
    setup_logging()
    torch.hub.set_dir('/tmp/weights')
    predict()
