---
name: watch
channels:
  - conda-forge
dependencies:
  - python=3.8
  - gdal
  - git
  - shapely=1.7.1
  - pip
  - pip:
    - git+https://github.com/BeamIO-Inc/algorithm_toolkit.git@master
    - numpy==1.19.5
    - Pillow==7.1.0
    - requests==2.20.0
