# Autogenerated via:
# python ~/code/watch/dev/maintain/mirror_package_geowatch.py
from geowatch.tasks.fusion.evaluate import main


def __getattr__(key):
    import geowatch.tasks.fusion.evaluate as mirror
    return getattr(mirror, key)


def __dir__():
    import geowatch.tasks.fusion.evaluate as mirror
    return dir(mirror)


if __name__ == '__main__':
    # import xdev
    # xdev.make_warnings_print_tracebacks()
    main()
