# Autogenerated via:
# python ~/code/watch/dev/maintain/mirror_package_geowatch.py
from geowatch.tasks.landcover.predict import setup_logging, predict


def __getattr__(key):
    import geowatch.tasks.landcover.predict as mirror
    return getattr(mirror, key)


def __dir__():
    import geowatch.tasks.landcover.predict as mirror
    return dir(mirror)


if __name__ == '__main__':
    setup_logging()
    predict()
