# Autogenerated via:
# python ~/code/watch/dev/maintain/mirror_package_geowatch.py
from geowatch.tasks.cold.tile_processing_kwcoco import tile_process_main


def __getattr__(key):
    import geowatch.tasks.cold.tile_processing_kwcoco as mirror
    return getattr(mirror, key)


def __dir__():
    import geowatch.tasks.cold.tile_processing_kwcoco as mirror
    return dir(mirror)


if __name__ == '__main__':
    tile_process_main()
