# Autogenerated via:
# python ~/code/watch/dev/maintain/mirror_package_geowatch.py
from geowatch.tasks.cold.transfer_features import transfer_features_main


def __getattr__(key):
    import geowatch.tasks.cold.transfer_features as mirror
    return getattr(mirror, key)


def __dir__():
    import geowatch.tasks.cold.transfer_features as mirror
    return dir(mirror)


if __name__ == '__main__':
    transfer_features_main()
