apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ta2-train-
  annotations:
    email: 'jon.crall@kitware.com'
    purpose: |
      Check read access on DVC GitLab repo
    submitter: 'Jon Crall'
spec:
  entrypoint: ta2-train-init
  serviceAccountName: argo-runner
  imagePullSecrets:
    - name: gitlab-pull-secret
  nodeSelector:
    kitware.com/node-pool: standard
  volumes:
    - name: dvc-access-secret-volume
      secret:
        secretName: dvc-gitlab-access-token
  templates:
  - name: ta2-train-init
    container:
      #image: gitlab.kitware.com:4567/smart/watch/training:{{inputs.parameters.container_tag}}
      #image: gitlab.kitware.com:4567/smart/watch/ta2_training_v2:{{inputs.parameters.container_tag}}
      #image: gitlab.kitware.com:4567/smart/watch/ta2_training_v2:981feb6592f2
      image: gitlab.kitware.com:4567/smart/watch/ta2_training_v2
      command: [bash]
      args: ["/root/code/watch/aws/train_remote_init.sh"]
      resources:
        requests:
          memory: "1000Mi"
          cpu: "1000m"
        limits:
          memory: "2000Mi"
          cpu: "1500m"
      env:
        - name: DVC_GITLAB_USERNAME
          valueFrom:
            secretKeyRef:
              name: dvc-gitlab-access-token
              key: username
        - name: DVC_GITLAB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dvc-gitlab-access-token
              key: password
        - name: WATCH_REPO_GITLAB_RO_DEPLOY_USERNAME
          valueFrom:
            secretKeyRef:
              name: watch-repo-gitlab-ro-deploy-token
              key: username
        - name: WATCH_REPO_GITLAB_RO_DEPLOY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: watch-repo-gitlab-ro-deploy-token
              key: password
      volumeMounts:
        - name: dvc-access-secret-volume
          mountPath: "/secret/dvc-access-secret-mountpath"
