# Autogenerated via:
# python ~/code/watch/dev/maintain/mirror_package_geowatch.py
from watch.tasks.cold.writing_kwcoco import cold_writing_kwcoco_main


def __getattr__(key):
    import watch.tasks.cold.writing_kwcoco as mirror
    return getattr(mirror, key)


def __dir__():
    import watch.tasks.cold.writing_kwcoco as mirror
    return dir(mirror)


if __name__ == '__main__':
    cold_writing_kwcoco_main()
