# Autogenerated via:
# python ~/code/watch/dev/maintain/mirror_package_geowatch.py


def __getattr__(key):
    import geowatch.tasks.rutgers_material_change_detection.models.patch_transformer as mirror
    return getattr(mirror, key)


def __dir__():
    import geowatch.tasks.rutgers_material_change_detection.models.patch_transformer as mirror
    return dir(mirror)


if __name__ == '__main__':
    frame_size = 40
    n_channels = 4
    patch_size = 20
    n_frames = 5
    encoder = PatchTransformerEncoder("total_bin_mode", n_channels, frame_size, patch_size, n_frames)
    test_input = torch.zeros([1, n_frames, n_channels, frame_size, frame_size])
    output = encoder(test_input)
