# Autogenerated via:
# python ~/code/watch/dev/maintain/mirror_package_geowatch.py


def __getattr__(key):
    import geowatch.tasks.rutgers_material_change_detection.models.timesformer as mirror
    return getattr(mirror, key)


def __dir__():
    import geowatch.tasks.rutgers_material_change_detection.models.timesformer as mirror
    return dir(mirror)


if __name__ == '__main__':
    # Test 1: Just call model correctly.
    model = TimeSformer()
