# Autogenerated via:
# python ~/code/watch/dev/maintain/mirror_package_geowatch.py
from watch.tasks.rutgers_material_seg_v2.predict import predict


def __getattr__(key):
    import watch.tasks.rutgers_material_seg_v2.predict as mirror
    return getattr(mirror, key)


def __dir__():
    import watch.tasks.rutgers_material_seg_v2.predict as mirror
    return dir(mirror)


if __name__ == '__main__':
    predict()
