# Autogenerated via:
# python ~/code/watch/dev/maintain/mirror_package_geowatch.py
from geowatch.__main__ import main


def __getattr__(key):
    import geowatch.__main__ as mirror
    return getattr(mirror, key)


def __dir__():
    import geowatch.__main__ as mirror
    return dir(mirror)


if __name__ == '__main__':
    main()
