# Autogenerated via:
# python ~/code/watch/dev/maintain/mirror_package_geowatch.py
from geowatch.demo.metrics_demo.generate_demodata import main


def __getattr__(key):
    import geowatch.demo.metrics_demo.generate_demodata as mirror
    return getattr(mirror, key)


def __dir__():
    import geowatch.demo.metrics_demo.generate_demodata as mirror
    return dir(mirror)


if __name__ == '__main__':
    main()
