# Ours
# location: server
location: local
data:
  type: classification
  name: bigearthnet
  num_classes: 19
  window_size: 7
  image_size: 120 #pre-train: 32, fine_tune: 96
  time_steps: 2
  weights: [0.1, 1.0]
  # channels: B02|B03|B04|B05|B06|B07|B08|B11|B12|B8A
  channels: B02|B03|B04|B05|B06|B07|B08|B11|B12
  local:
    model_save_dir: /home/native/projects/data/smart_watch/models/
    train_dir: /media/native/data2/data/BigEarthNet-S2-v1.0/BigEarthNet-v1.0/
    test_dir: /media/native/data2/data/BigEarthNet-S2-v1.0/BigEarthNet-v1.0/
    train_coco_json: 
    test_coco_json: 
    val_dir:
  server:
    model_save_dir: /data4/peri/smart_watch/models/
    train_dir: /data4/datasets/BigEarthNet-S2-v1.0/BigEarthNet-v1.0/
    test_dir: /data4/datasets/BigEarthNet-S2-v1.0/BigEarthNet-v1.0/
    val_dir: /data4/datasets/BigEarthNet-S2-v1.0/BigEarthNet-v1.0/
    train_coco_json: 
    test_coco_json:

training:
  backbone: resnet34 #resnet18 #resnet101, resnet50, resnet34
  model_name: resnet_class_ft #shallow_seg, deeplabWS, deeplab, resnet, resnet_enc, resnetGNWS, resnet_class_ft
  model_feats_channels: [64, 128, 256, 512, 256] #[32, 32, 64, 64, 128], [64, 64, 128, 256, 512], [32, 32, 64, 128, 256], [64, 128, 256, 512, 1024] # this needs to match the correct number of layers in the model
  gn_n_groups: 32
  num_channels: 9
  out_features_dim: 10
  weight_std: True
  beta: False
  # pretrained: /home/native/projects/data/smart_watch/models/experiments_onera/tasks_experiments_onera_2021-10-19-21:07/experiments_epoch_5_loss_2.1330662268512652_valmF1_0.6782787764504841_valChangeF1_0.47969179367601383_time_2021-10-20-03:39:36.pth
  pretrained: False
  distributed: False
  learning_rate: 0.001 # best: 
  # resume: /home/native/projects/data/smart_watch/models/experiments_onera/tasks_experiments_onera_2021-10-07-10:23/experiments_epoch_7_loss_3440.9182313163324_valmIoU_0.5437659117662471_time_2021-10-07-20:47:20.pth
  # resume: /home/native/projects/data/smart_watch/models/experiments_onera/tasks_experiments_onera_2021-10-20-17:15/experiments_epoch_37_loss_7.454268312454223_valmF1_0.7629152048972937_valChangeF1_0.5579948695099214_time_2021-10-20-18:04:59.pth
  resume: False
  train_val_test_split: [0.95, 0.02, 0.03]
  epochs: 200
  start_epoch: 0
  batch_size: 16
  drop_last_batch: True
  momentum: 0.3
  weight_decay: 0.0001
  num_workers: 0
  test_with_full_supervision: 1
  model_single_input: False
  n_samples: 25

high_confidence_threshold:
  train_cutoff: 0.4
  val_cutoff: 0.4
  train_low_cutoff: 0.0
  val_low_cutoff: 0.0

evaluation:
  use_crf: False
  crf_t: 1
  crf_scale_factor: 1
  inference_window: 13
  batch_size: 32

procedures:
  train:  True
  validate: True
