# Autogenerated via:
# python ~/code/watch/dev/maintain/mirror_package_geowatch.py
from geowatch.tasks.rutgers_material_seg.predict_test import main


def __getattr__(key):
    import geowatch.tasks.rutgers_material_seg.predict_test as mirror
    return getattr(mirror, key)


def __dir__():
    import geowatch.tasks.rutgers_material_seg.predict_test as mirror
    return dir(mirror)


if __name__ == '__main__':
    main()
