# Autogenerated via:
# python ~/code/watch/dev/maintain/mirror_package_geowatch.py
from geowatch.utils.process_context import main


def __getattr__(key):
    import geowatch.utils.process_context as mirror
    return getattr(mirror, key)


def __dir__():
    import geowatch.utils.process_context as mirror
    return dir(mirror)


if __name__ == '__main__':
    main()
