# Autogenerated via:
# python ~/code/watch/dev/maintain/mirror_package_geowatch.py
from geowatch.tasks.fusion.datamodules.qa_bands import demo


def __getattr__(key):
    import geowatch.tasks.fusion.datamodules.qa_bands as mirror
    return getattr(mirror, key)


def __dir__():
    import geowatch.tasks.fusion.datamodules.qa_bands as mirror
    return dir(mirror)


if __name__ == '__main__':
    demo()
