# Autogenerated via:
# python ~/code/watch/dev/maintain/mirror_package_geowatch.py
from geowatch.demo.demo_region import demo_khq_region_fpath


def __getattr__(key):
    import geowatch.demo.demo_region as mirror
    return getattr(mirror, key)


def __dir__():
    import geowatch.demo.demo_region as mirror
    return dir(mirror)


if __name__ == '__main__':
    demo_khq_region_fpath()
