# Autogenerated via:
# python ~/code/watch/dev/maintain/mirror_package_geowatch.py
from geowatch.demo.stac_demo import print


def __getattr__(key):
    import geowatch.demo.stac_demo as mirror
    return getattr(mirror, key)


def __dir__():
    import geowatch.demo.stac_demo as mirror
    return dir(mirror)


if __name__ == '__main__':
    print(demo())
