# Autogenerated via:
# python ~/code/watch/dev/maintain/mirror_package_geowatch.py
def __getattr__(key):
    import watch.tasks.dino_detector.building_validator as mirror
    return getattr(mirror, key)