# Autogenerated via:
# python ~/code/watch/dev/maintain/mirror_package_geowatch.py
from geowatch.mlops.confusor_analysis import main


def __getattr__(key):
    import geowatch.mlops.confusor_analysis as mirror
    return getattr(mirror, key)


def __dir__():
    import geowatch.mlops.confusor_analysis as mirror
    return dir(mirror)


if __name__ == '__main__':
    main()
