# Autogenerated via:
# python ~/code/watch/dev/maintain/mirror_package_geowatch.py
from geowatch.utils.lightning_ext.callbacks.tensorboard_plotter import fire


def __getattr__(key):
    import geowatch.utils.lightning_ext.callbacks.tensorboard_plotter as mirror
    return getattr(mirror, key)


def __dir__():
    import geowatch.utils.lightning_ext.callbacks.tensorboard_plotter as mirror
    return dir(mirror)


if __name__ == '__main__':
    import fire
    fire.Fire(redraw_cli)
