# Autogenerated via:
# python ~/code/watch/dev/maintain/mirror_package_geowatch.py
from geowatch.cli.run_tracker import main


def __getattr__(key):
    import geowatch.cli.run_tracker as mirror
    return getattr(mirror, key)


def __dir__():
    import geowatch.cli.run_tracker as mirror
    return dir(mirror)


if __name__ == '__main__':
    main(sys.argv[1:])
